ARG TAG
FROM ghcr.io/odrling/chimera:$TAG
RUN apk upgrade && apk add chimera-repo-contrib && apk add musl-devel base-cross pkgconf meson clang git llvm lld base-cross mold go nodejs libgcc-chimera qemu-user chimerautils ffmpeg buildah podman && mkdir -p /__e/node20/bin/ && ln /usr/bin/node /__e/node20/bin/node
